discordjs-japan/om

src/commands/leave.ts
editReplyに到達せず，メッセージがdeferのままになってしまう問題がありました．
問題はstateChangeは同期的に呼ばれるところにあったようですので，setImmediateで対応しました．
（コメントの英語が不自然かもしれないので，代案を歓迎します）
https://github.com/discordjs/discord.js/blob/ce0be392d818b13ba5a081811519b559202cdba8/packages/voice/src/VoiceConnection.ts#L564-L566
=> Fix leave message is never edited

Dockerfile
18.19.0 では npm v10.2.3 がバンドルされているため、
GitHub Actions 上でのコンテナ構築に失敗するから。
=> Pin to Node.js 18.18.2

Dockerfile
builderステップ，model-fetchステップはアーキテクチャ依存のファイルを含まないため，ビルド環境のアーキテクチャのみで実行すれば十分です．qemuでビルドされる部分を減らすことで，ビルド時間を短縮します．
=> Update node.js (& shorten build time)

.github/workflows/ci.yml, Dockerfile, package-lock.json, package.json
Closes #18 
Release-As: 0.1.1
debian 12を採用していることによりopusのprebuildが利用できていないため，実はNode 20に上げても上げなくてもopusのビルドは走っていたようです．
なお，`20.10.0`ではなく`20.10.0-bookworm`としたのは，depsステージでもdebian 12を使わせるためです．現在は最新版がbookwormなので違いはありませんが，今後新しいバージョンが出てきたときに壊れないよう，bookwormに固定します．
=> build: update node to v20

.github/workflows/release.yml
このリポジトリ以外でリリース処理を行う場合、リリースに関係する記載を書き換えるはずであるしそうして然るべきである。
それ故、このワークフローは discordjs-japan org 内でのみ動くようにするとともに、ここでその旨を明確にする。
=> ci: restrict release workflow to discordjs-japan

src/commands/join.ts, src/pipeline.ts
fix #55 
fix #56 
fix #57
1つのメッセージが読み上げられる回数がbotをvcから抜けさせて再接続するごとに増えていく。
#55: 原因はMessageCollectorがleaveコマンド実行時に適切に終了されなかったことで、`Synthesizer#dispatchSynthesis`がleaveコマンドの実行回数+1回呼ばれていたこと。
#56,#57: ハンドリングしてない
VoiceConnectionのライフサイクルを考慮して適切になるようにdestroy時に呼ばれる処理を修正し、その他Pipelineのライフサイクルが適切になるように修正した。
- botがすでにVCに接続している=>エラーメッセージを直ちに返す
- botがVCに接続できない=>権限の不足でエラーにできる場合は直ちにエラーにし、できない場合には15s後にエラーメッセージを返す
- botが切断させられる=>切断する
- botがチャンネル移動させられる=>切断する
=> fix: improper handling voice connection status change

package-lock.json, package.json
node-altjtalk-bindingを0.1.4にアップデートします．
Windowsでインストールできない問題と，上流のjpreprocessのバグ（「――酒」の酒が読み上げられない件）が修正されます．
=> deps: update node-altjtalk-binding to v0.1.4

build.js, package-lock.json, package.json, src/main.ts, src/version.ts
Closes #72 
懸念点として，package.jsonをインポートしたことで，main.jsにpackage.jsonの内容がすべて書かれるという問題があります．
=> feat: Show version as an activity

src/synthesis/options.ts
createSynthesisOptionにて，`message.author.id`を用いて声がある程度ばらけるように実装しました．同じ`message.author.id`に対しては同じ`SynthesisOption`を返します．
=> feat: return varied synthesis options by primitive rng

src/synthesis/clean.ts
```
SyntaxError: Named export 'parserFor' not found. The requested module 'simple-markdown' is a CommonJS module, which may not support all module.exports as named exports.
```
=> fix: default import SimpleMarkdown

Dockerfile
multi-platform imagesをビルドするときに、cacheが使われるようにする
=> build: add variables

package-lock.json, package.json, src/synthesis/common.ts, src/synthesis/index.ts, src/synthesis/worker-synthesizer.ts
バージョンが変わる以外の主要な変更点
- 環境変数`MODEL`が`MODELS`に変わり，書式が`string[]`のJSONになります．
- 複数のモデルを指定できるようになります．
- 同時に使えるモデルの組み合わせには制限があります．tohoku-f01のneutral/happy/sad/angryは同時に使えるはずです．
- `USER_DICTIONARY`環境変数を介して，ユーザー辞書を使えるようになります．
=> deps: Update node-altjtalk-binding to v0.2.0

.github/.config/release-please-config.json, .github/workflows/release.yml
コンテナイメージの publish が終わってからリリースを行うようにします
=> ci: publish Docker image before releasing

.github/workflows/cleanup-caches.yml
- `4m-mazi/souji-action` を使うようにします
- head ref のキャッシュは ブランチが削除された時に消すようにします
=> ci: use souji-action for cleanup

build.js
Node.js v20.10.0 にて Import attributes に変更されました
see: https://nodejs.org/docs/v20.12.0/api/esm.html#import-attributes
=> build: Switch from Import Assertions to Import Attributes

compose.yaml
Makes it possible to avoid container name conflicts.
=> chore: remove `container_name` specification

src/main.ts
=> feat: assign process.title

.husky/pre-commit
ref: https://github.com/typicode/husky/releases/tag/v9.1.1
=> chore(husky): `npx` is no longer needed

Dockerfile
- digest pinningしているので、メジャーのみ指定することによる恩恵を受けてないから
=> build: specify Dockerfile syntax down to the patch version

src/main.ts
=> fix: set activity with ClientOptions

.gitattributes
=> chore: exclude scripts directory from linguist detection

src/synthesis/clean.ts
=> fix: update regex to allow spaces in slash command name

src/synthesis/clean.test.ts, src/synthesis/clean.ts
クライアントでは discordapp.com でも discord のリンクであると判断されるため，それらを追加。
=> fix: add *.discordapp.com to allowed host list

src/synthesis/clean.test.ts, src/synthesis/clean.ts
`<t:253402300740>` などを読み上げる際，最後に「GMTたす9」がつくバグの修正。
=> fix: fix a bug of dateSegments()

package-lock.json, package.json
This package is a stub type definition and is not needed because @eslint/js provides its own type definitions.
=> chore(deps-dev): remove unnecessary @types/eslint__js

eslint.config.js
see: https://github.com/prettier/eslint-config-prettier/blob/v10.1.1/CHANGELOG.md#patch-changes
=> chore: update eslint-config-prettier import to use `/flat` entry
