discordjs-japan/om

src/pipeline.ts, src/synthesis/index.ts, src/synthesis/options.ts, src/synthesis/stream.ts, src/synthesis/synthesizer.ts, src/synthesis/worker-pool.ts, src/synthesis/worker-synthesizer.ts
なんかEventEmitterの型周りも色々いじってますが……
=> singleton synthesizer

package-lock.json, package.json, tsconfig.json
=> Add dotenv

package.json, tsconfig.json
https://github.com/TypeStrong/ts-node/issues/1997
=> fix ts-node on node v20

src/main.ts
dockerで起動した際，SIGINT/SIGTERMで終了しないので，自前のハンドラを入れました．
=> Handle sigint/sigterm

Dockerfile, README.md, src/synthesis/index.ts
デプロイ手順を簡略化するため，辞書とモデルをDockerコンテナに含めることにしました．
Closes #9
=> Model inside container

.github/.config/release-please-config.json
=> ci: override changelog-sections for deps 

.npmrc
=> chore: set save-exact true

package-lock.json, package.json
=> deps: update altjtalk to v0.1.5

package-lock.json, package.json
ごめんなさい…
altjtalk側のpackage.jsonを更新するのを忘れていました……
=> deps: update node-altjtalk-binding to v0.1.6

src/commands/skip.ts, src/main.ts, src/pipeline.ts
=> feat: add skip command

package-lock.json, package.json, src/synthesis/clean.test.ts, src/synthesis/clean.ts, src/synthesis/worker-synthesizer.ts
=> feat: clean text before synthesis

.github/workflows/cleanup-caches.yml
プルリクエストのクローズ または 手動操作 をトリガーとして、当該ブランチに紐づいたキャッシュを削除します。
=> ci: add cleanup-caches workflow

.prettierignore
=> chore: add .prettierignore

src/main.ts
=> feat: leave the voice channel when alone

src/env.ts, src/synthesis/index.ts, src/synthesis/worker-synthesizer.ts
`MODELS`がJSONからカンマ区切りに変わっています．
=> feat: Centralized env

Dockerfile, README.md, src/env.ts
Q: 破壊的変更ではないのですか？
A: 変更前のREADMEでは「付属のDockerfileで定義されたイメージを使ってください」とだけ書いてありました．この方法についてはbreakingではないため，破壊的ではありません．
=> feat: Well documented env

src/synthesis/clean.test.ts, src/synthesis/clean.ts
=> feat: clean command mention

src/synthesis/ignore.test.ts, src/synthesis/ignore.ts, src/synthesis/worker-synthesizer.ts
closes: #146
括弧の中身を無視します．括弧が開きっぱなしで最後まで行った場合はすべて無視します．
=> feat: ignore paren content

src/synthesis/clean.test.ts, src/synthesis/clean.ts
=> fix: just omit discord non-channel url

Dockerfile
https://docs.docker.com/reference/dockerfile/#benefits-of-using---link
https://docs.docker.com/reference/dockerfile/#incompatibilities-with---linkfalse
=> build: use `link` option at COPY instruction

.github/workflows/release.yml
ref: https://github.com/google-github-actions/release-please-action/blob/e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee/README.md#migration
=> ci: migrate release-please-action

Dockerfile
This reverts commit 2240357413e01148e9198ff6530e42d77101419a.
=> revert: "build: use JPREPROCESS_VERSION (#374)"

Dockerfile
=> build: Dockerfile better download

src/commands/skip.ts, src/pipeline.ts, src/synthesis/index.ts
=> feat: change message on skip

package-lock.json, package.json
=> deps: bye discordjs/opus

src/pipeline.ts
=> fix: fix timing to cache Pipeline

src/pipeline.ts
=> fix: delete Pipeline#playing when idle

src/pipeline.ts
Closes: #411 
Co-authored-by: Mogyuchi <mogyuchi@mogyuchi.jp>
=> feat: Don't start speaking when humans are speaking

src/pipeline.ts, src/synthesis/index.ts
=> fix: skip playing if there is no readable content

src/pipeline.ts
ref: #449, https://github.com/discordjs-japan/om/actions/runs/9617911127/job/26530691283
=> fix: use built-in EventEmitter typing

.github/workflows/docker-publish.yml
=> build: delete org.opencontainers.image.licenses label

src/pipeline.ts, src/synthesis/index.ts
This reverts commit 6a3bb6ae8ff61df2f5a0082a3b6cc925d903b958.
このHACKは不要になりました
=> revert: "resolve type issues"

src/commands/join.ts, src/commands/leave.ts, src/commands/skip.ts, src/commands/version.ts
=> fix: make slash commands usable only within the server

src/pipeline.ts
related: https://github.com/discordjs-japan/om/pull/568
=> refactor: remove unnecessary type casting for voice adapter creator

package-lock.json, package.json, tsconfig.json
close: #668 
代償として、type check機能がなくなります。
=> chore: switch ts-node to tsx

scripts/build.js
https://esbuild.github.io/getting-started/#bundling-for-node
https://esbuild.github.io/api/#packages
=> chore: simplify build config using `packages` option

package-lock.json, package.json
=> chore: remove dotenv

src/synthesis/clean.ts
=> fix: update discord url validation to include ptb.discord.com

.release-please/release-please-config.json
related: #706
https://github.com/googleapis/release-please/blob/v16.12.0/docs/customizing.md#updating-arbitrary-files
=> chore: add README.md to extra files in release-please config

src/commands/skip.ts, src/commands/version.ts, src/error.test.ts, src/error.ts
=> refactor: "ephemeral" is deprecated

src/commands/join.ts
=> feat: improve join command to use interaction channel as default

src/synthesis/text/attachments.test.ts, src/synthesis/text/attachments.ts, src/synthesis/text/clean.ts, src/synthesis/text/index.ts
=> feat: Process MessageReference and Attachments

tsconfig.eslint.json
`npm exec -- tsc --project tsconfig.eslint.json` で確認
=> chore: update tsconfig.eslint.json to exclude node_modules and dist directories

src/synthesis/text/index.ts
=> fix: resolve user display name from guild member in message reference
